spring.application.name=oktaauthentication


server.port=8081

# OKTA
okta.org.url=https://trial-4059981.okta.com
okta.api.token=008B0OINHiHAeHa98TO1O6NdvJfNMEwG3t8czSl44n
#okta.api.token=00OLsNqILocum33ldF8Ju_liPY4fSRqWYyAajdvndB
#okta.api.token=009-bJWvp817PB024d1p3DgUFZql68befDsYiVpyX_
okta.authn.path=/api/v1/authn
# Okta get user groups API
okta.users.groups.path=/api/v1/users/{login}/groups
# Okta get user by login API
okta.users.by-login.path=/api/v1/users/{login}
# Okta create user API
okta.users.create.path=/api/v1/users?activate=true
# Okta assign user to group (role) API
okta.groups.assign-user.path=/api/v1/groups/{groupId}/users/{userId}


# ===== OKTA GROUP IDS =====
okta.group.user=00gybnga2kQvxdjFE697
okta.group.loan-officer=00gybnexcl1DtDpKm697
okta.group.admin=00gybnechxEWlty7E697

okta.group.clientID=0oayj23rwhZrGfhCu697
okta.group.client.secret=VqIIvTzOgMewW8Uwk7as-NxWvXvlGYpeA7Jl_8x0SupbFWibZZhrnQLezqnWvA4i


jwt.secret=8fK9!dPq3#M2Z@R6Lx7B0aN$YHcE4WJvS1U
jwt.expiration=3600000

