spring.application.name=Contact_Manager_Application
spring.datasource.url=jdbc:postgresql://localhost:5432/HotelManagement
spring.datasource.username=postgres
spring.datasource.password=hrutwik2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true